/**
 * Tuesday weekly-reads autofeed · Wave 16.1
 *
 * Scheduled Netlify Function that runs every Tuesday at 1pm UTC (8am ET
 * during EST, 9am during EDT). Calls the shared `curateWeeklyReadsFromWeb`
 * helper to pull 3 fresh multifamily articles from the past week, then
 * auto-publishes them to the `weeklyReads` blob with `autoGenerated: true`.
 *
 * Both Mastery and Self-Study dashboards read this blob, so the Tuesday
 * cycle refreshes both surfaces simultaneously without any human action.
 *
 * Admin override: Lou and Diva can publish their own set any day via
 * /admin/weekly-reads. That sets autoGenerated: false. The next Tuesday
 * cron run replaces it with a fresh autofeed unless we add a "lock" flag
 * later. For now, manual publishes get rolled over weekly — keep that in
 * mind if you want a particular article to stick.
 *
 * Failure modes (all silent except for logs):
 *   - ANTHROPIC_API_KEY missing → log + skip
 *   - Claude API error → log + skip
 *   - Empty article list → log + skip (existing blob remains live)
 *
 * Cost: ~$0.01-0.02 per Tuesday run (Claude Haiku + 3 web search calls).
 */

import type { Config } from '@netlify/functions';
import { saveWeeklyReads, type WeeklyReadsBlob } from './_lib/store';
import { curateWeeklyReadsFromWeb } from './_lib/curate';

export default async (_req: Request): Promise<Response> => {
  const startedAt = Date.now();
  console.log('[scheduled-weekly-reads] start');

  const result = await curateWeeklyReadsFromWeb(3);
  if (!result || !result.articles.length) {
    const summary = {
      ok: false,
      reason: 'no articles returned from curation',
      durationMs: Date.now() - startedAt,
    };
    console.warn('[scheduled-weekly-reads] skipped', summary);
    return new Response(JSON.stringify(summary), {
      status: 200,
      headers: { 'content-type': 'application/json' },
    });
  }

  const blob: WeeklyReadsBlob = {
    publishedAt: new Date().toISOString(),
    publishedBy: 'autofeed@scheduled',
    autoGenerated: true,
    articles: result.articles,
  };

  try {
    await saveWeeklyReads(blob);
  } catch (err) {
    console.error('[scheduled-weekly-reads] save error', err);
    return new Response(
      JSON.stringify({ ok: false, reason: 'save error', durationMs: Date.now() - startedAt }),
      { status: 200, headers: { 'content-type': 'application/json' } },
    );
  }

  const summary = {
    ok: true,
    articleCount: result.articles.length,
    durationMs: Date.now() - startedAt,
  };
  console.log('[scheduled-weekly-reads] complete', summary);
  return new Response(JSON.stringify(summary), {
    status: 200,
    headers: { 'content-type': 'application/json' },
  });
};

export const config: Config = {
  // 13:00 UTC every Tuesday ≈ 8am ET (EST) / 9am ET (EDT).
  // Lou and Diva can override any day via /admin/weekly-reads — the next
  // Tuesday tick will replace the override with a fresh autofeed.
  schedule: '0 13 * * 2',
};
