import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/router';
import Card from '@/components/Card';
import Button from '@/components/Button';
import Input from '@/components/Input';
import { useAuth } from '@/hooks/useAuth';
import { api, ApiError } from '@/lib/api';

/**
 * Admin · /admin/weekly-reads · Wave 16.1
 *
 * Lou and Diva publish the "What we're reading this week" set here.
 * Five rows by default (typical 3-5 articles); rows can be left blank
 * if you only have 3 to share this week — empty rows are dropped on
 * publish.
 *
 * The same blob is read by:
 *   - Mastery dashboard (this site, fetches /api/weekly-reads)
 *   - Self-Study dashboard (cross-site, fetches Mastery's public API)
 *
 * Editorial workflow: open this page Tuesday morning, paste 3-5 article
 * links + titles + sources + a one-line "why this matters" framing,
 * click Publish. Both dashboards reflect within ~60 seconds (CDN cache).
 */

interface ArticleRow {
  source: string;
  dateLabel: string;
  title: string;
  why: string;
  href: string;
}

const EMPTY_ROW: ArticleRow = {
  source: '',
  dateLabel: '',
  title: '',
  why: '',
  href: '',
};

// Wave 16.1 · default 3 rows. Admin can extend up to 5 max via "Add another".
// The Tuesday autofeed cron also publishes 3 articles by default.
const INITIAL_ROWS: ArticleRow[] = [
  { ...EMPTY_ROW },
  { ...EMPTY_ROW },
  { ...EMPTY_ROW },
];

const MAX_ROWS = 5;

interface CurrentBlobResponse {
  blob: {
    publishedAt: string;
    publishedBy: string;
    autoGenerated?: boolean;
    articles: ArticleRow[];
  } | null;
}

export default function AdminWeeklyReadsPage() {
  const router = useRouter();
  const { user, loading } = useAuth();
  const [rows, setRows] = useState<ArticleRow[]>(INITIAL_ROWS);
  const [busy, setBusy] = useState(false);
  const [refreshing, setRefreshing] = useState(false);
  const [err, setErr] = useState<string | null>(null);
  const [publishedAt, setPublishedAt] = useState<string | null>(null);
  const [publishedBy, setPublishedBy] = useState<string | null>(null);
  const [autoGenerated, setAutoGenerated] = useState<boolean>(false);
  const [savedNote, setSavedNote] = useState<string | null>(null);

  // Auth gate
  useEffect(() => {
    if (loading) return;
    if (!user) router.replace('/login');
    else if (!user.isAdmin) router.replace('/dashboard');
  }, [loading, user, router]);

  // Initial load · pre-populate rows from the current published blob
  useEffect(() => {
    if (!user?.isAdmin) return;
    void load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [user?.isAdmin]);

  async function load() {
    setErr(null);
    try {
      const data = await api<CurrentBlobResponse>('/api/admin/weekly-reads');
      if (data.blob && data.blob.articles?.length) {
        // Show exactly the published rows for editing — admin can hit
        // "Add another" up to 5 max if they want to extend the set.
        setRows(data.blob.articles.slice(0, MAX_ROWS));
        setPublishedAt(data.blob.publishedAt);
        setPublishedBy(data.blob.publishedBy);
        setAutoGenerated(Boolean(data.blob.autoGenerated));
      }
    } catch (e) {
      const msg = e instanceof ApiError ? e.message : 'Unable to load current weekly reads';
      setErr(msg);
    }
  }

  /**
   * Wave 16.1 · "Refresh from autofeed" — calls the suggest endpoint,
   * which uses Claude with web_search to pull 3 fresh multifamily articles
   * from the past week. Replaces the form rows with the suggestions.
   * Admin reviews / edits / swaps / deletes individual rows before
   * clicking Publish — nothing goes live until Publish.
   */
  async function refreshFromAutofeed() {
    if (!confirm('Pull 3 fresh article suggestions from the past week? This will replace what\'s in the form (your last Publish stays live until you Publish again).')) {
      return;
    }
    setRefreshing(true);
    setErr(null);
    setSavedNote(null);
    try {
      const data = await api<{ articles: ArticleRow[] }>(
        '/api/admin/suggest-weekly-reads',
        { method: 'POST', body: {} },
      );
      if (!data.articles || data.articles.length === 0) {
        setErr('Autofeed returned no articles. Check Function logs and try again.');
        return;
      }
      // Replace the form rows with the suggestions; pad to at least 3 rows
      // (so the admin can keep adding their own beneath the suggestions).
      const next = [...data.articles];
      while (next.length < INITIAL_ROWS.length) next.push({ ...EMPTY_ROW });
      setRows(next);
      setSavedNote(`Loaded ${data.articles.length} fresh suggestions. Edit / delete / swap as you like, then Publish.`);
    } catch (e) {
      const msg = e instanceof ApiError ? e.message : 'Refresh failed';
      setErr(msg);
    } finally {
      setRefreshing(false);
    }
  }

  function updateRow(idx: number, field: keyof ArticleRow, value: string) {
    setRows((prev) =>
      prev.map((r, i) => (i === idx ? { ...r, [field]: value } : r))
    );
    setSavedNote(null);
  }

  function addRow() {
    setRows((prev) => (prev.length >= MAX_ROWS ? prev : [...prev, { ...EMPTY_ROW }]));
  }

  function removeRow(idx: number) {
    setRows((prev) => prev.filter((_, i) => i !== idx));
  }

  async function publish(e: FormEvent) {
    e.preventDefault();
    setErr(null);
    setSavedNote(null);

    // Drop empty rows; require source + title + href on every kept row
    const filled = rows.filter(
      (r) => r.source.trim() && r.title.trim() && r.href.trim()
    );
    if (!filled.length) {
      setErr('Add at least one article (source + title + href required).');
      return;
    }
    if (filled.length > MAX_ROWS) {
      setErr(`Maximum ${MAX_ROWS} articles per week.`);
      return;
    }
    // Validate hrefs
    for (const r of filled) {
      if (!/^https?:\/\//i.test(r.href.trim())) {
        setErr(`"${r.title}" — link must start with http:// or https://`);
        return;
      }
    }

    setBusy(true);
    try {
      const data = await api<{ ok: boolean; blob: CurrentBlobResponse['blob'] }>(
        '/api/admin/weekly-reads',
        {
          method: 'POST',
          body: { articles: filled },
        }
      );
      if (data.blob) {
        setPublishedAt(data.blob.publishedAt);
        setPublishedBy(data.blob.publishedBy);
        setAutoGenerated(Boolean(data.blob.autoGenerated));
      }
      setSavedNote(`Published ${filled.length} article${filled.length === 1 ? '' : 's'}.`);
    } catch (e) {
      const msg = e instanceof ApiError ? e.message : 'Publish failed';
      setErr(msg);
    } finally {
      setBusy(false);
    }
  }

  if (loading || !user || !user.isAdmin) {
    return (
      <main className="page page-center">
        <div className="container text-center text-ink-dim">Loading…</div>
      </main>
    );
  }

  return (
    <>
      <main className="page">
        <div className="container grid gap-8">
          <Card variant="hero">
            <div className="flex flex-col gap-2">
              <span className="eyebrow" style={{ color: 'var(--gold-bright)' }}>
                Admin · Weekly reads
              </span>
              <h3
                className="font-display font-medium"
                style={{ fontSize: 'clamp(28px, 3.5vw, 40px)', color: 'var(--cream)' }}
              >
                What we&rsquo;re reading this week.
              </h3>
              <p style={{ color: 'var(--cream-warm)', maxWidth: 720, lineHeight: 1.55 }}>
                Publish 3&ndash;5 multifamily articles every Tuesday. The same set
                renders on both the Mastery Live dashboard (this site) and the
                Self-Study dashboard (via cross-site fetch). Required per row:
                source, title, link. Date label and &ldquo;why this matters&rdquo; are
                strongly recommended.
              </p>
              <div className="flex gap-3" style={{ marginTop: 12 }}>
                <Link
                  href="/admin/deals"
                  className="btn-secondary"
                  style={{ borderColor: 'var(--gold)', color: 'var(--gold-bright)' }}
                >
                  Deals queue
                </Link>
                <Link
                  href="/admin/members"
                  className="btn-secondary"
                  style={{ borderColor: 'var(--gold)', color: 'var(--gold-bright)' }}
                >
                  Members
                </Link>
              </div>
            </div>
          </Card>

          {publishedAt && (
            <Card>
              <div className="flex flex-col gap-1">
                <span className="eyebrow">
                  Currently live{autoGenerated ? ' · autofeed' : ' · manual'}
                </span>
                <p className="text-ink-dim text-sm" style={{ margin: 0 }}>
                  Last published <strong style={{ color: 'var(--navy)' }}>
                    {new Date(publishedAt).toLocaleString()}
                  </strong>
                  {publishedBy ? (
                    <>
                      {' '}by <strong style={{ color: 'var(--navy)' }}>
                        {publishedBy === 'autofeed@scheduled' ? 'Tuesday autofeed' : publishedBy}
                      </strong>
                    </>
                  ) : null}
                  . Editing below replaces the live set on Save.
                  {autoGenerated && (
                    <>
                      {' '}<em>The next Tuesday autofeed cycle will replace this set unless you Publish your own first.</em>
                    </>
                  )}
                </p>
              </div>
            </Card>
          )}

          <Card style={{ background: 'var(--gold-soft)', borderColor: 'var(--gold)' }}>
            <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
              <div>
                <span className="eyebrow" style={{ color: 'var(--gold-deep)' }}>Autofeed</span>
                <p className="text-ink text-sm" style={{ margin: '4px 0 0', maxWidth: 560, lineHeight: 1.55 }}>
                  Pull 3 fresh article suggestions from this past week using
                  Claude web search. Replaces the form rows below. Review,
                  edit, swap individual rows, then click Publish to go live.
                  Available any day &mdash; the Tuesday autofeed cron does
                  this automatically every Tuesday at 8am ET.
                </p>
              </div>
              <Button
                type="button"
                onClick={() => void refreshFromAutofeed()}
                disabled={refreshing || busy}
                style={{ background: 'var(--gold)', borderColor: 'var(--gold)', whiteSpace: 'nowrap' }}
              >
                {refreshing ? 'Searching…' : 'Refresh from autofeed'}
              </Button>
            </div>
          </Card>

          {err && (
            <Card style={{ borderColor: '#b91c1c', borderWidth: 1, borderStyle: 'solid' }}>
              <p className="text-sm" style={{ color: '#b91c1c', margin: 0 }}>{err}</p>
            </Card>
          )}

          {savedNote && (
            <Card style={{ borderColor: '#16a34a', borderWidth: 1, borderStyle: 'solid' }}>
              <p className="text-sm" style={{ color: '#166534', margin: 0 }}>{savedNote}</p>
            </Card>
          )}

          <Card>
            <form onSubmit={publish} noValidate>
              <div className="flex flex-col gap-6">
                {rows.map((r, idx) => (
                  <div
                    key={idx}
                    style={{
                      paddingTop: idx === 0 ? 0 : 18,
                      borderTop: idx === 0 ? 'none' : '1px solid var(--line)',
                    }}
                  >
                    <div className="flex items-center justify-between" style={{ marginBottom: 12 }}>
                      <span
                        className="eyebrow"
                        style={{ color: 'var(--gold-deep)' }}
                      >
                        Article {idx + 1}
                      </span>
                      {rows.length > 1 && (
                        <button
                          type="button"
                          onClick={() => removeRow(idx)}
                          style={{
                            background: 'transparent',
                            border: 'none',
                            color: 'var(--ink-dim)',
                            fontSize: 12,
                            cursor: 'pointer',
                            textDecoration: 'underline',
                          }}
                        >
                          Remove
                        </button>
                      )}
                    </div>

                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
                      <Input
                        label="Source"
                        type="text"
                        placeholder="CBRE"
                        value={r.source}
                        onChange={(e) => updateRow(idx, 'source', e.target.value)}
                      />
                      <Input
                        label="Date label"
                        type="text"
                        placeholder="Apr 29"
                        value={r.dateLabel}
                        onChange={(e) => updateRow(idx, 'dateLabel', e.target.value)}
                      />
                    </div>
                    <Input
                      label="Title"
                      type="text"
                      placeholder="Multifamily Cap Rates Compress in Sun Belt Submarkets"
                      value={r.title}
                      onChange={(e) => updateRow(idx, 'title', e.target.value)}
                    />
                    <Input
                      label="Link (https://…)"
                      type="url"
                      placeholder="https://www.cbre.com/insights/articles/..."
                      value={r.href}
                      onChange={(e) => updateRow(idx, 'href', e.target.value)}
                    />
                    <Input
                      label="Why this matters (one line)"
                      type="text"
                      placeholder="A 10-min read before your next underwrite — the cap rate trajectory matters for exit pricing."
                      value={r.why}
                      onChange={(e) => updateRow(idx, 'why', e.target.value)}
                    />
                  </div>
                ))}
              </div>

              <div className="flex justify-between items-center" style={{ marginTop: 24, flexWrap: 'wrap', gap: 12 }}>
                <button
                  type="button"
                  onClick={addRow}
                  disabled={rows.length >= 8}
                  style={{
                    background: 'transparent',
                    border: '1px dashed var(--line)',
                    color: 'var(--ink-dim)',
                    padding: '8px 14px',
                    borderRadius: 4,
                    fontSize: 13,
                    cursor: rows.length >= 8 ? 'not-allowed' : 'pointer',
                  }}
                >
                  + Add another article (max 8)
                </button>

                <Button
                  type="submit"
                  disabled={busy}
                  style={{ background: 'var(--gold)', borderColor: 'var(--gold)' }}
                >
                  {busy ? 'Publishing…' : 'Publish to both dashboards'}
                </Button>
              </div>
            </form>
          </Card>

          <p className="text-ink-dim text-sm">
            Empty rows are dropped automatically on Publish. Required per article:
            source + title + link. Articles render with a max-280-char &ldquo;why&rdquo;
            framing under the title, so keep it tight.
          </p>
        </div>
      </main>

      <footer>
        <div className="container">
          <div className="footer-top">
            <div className="footer-brand">
              <Link href="/dashboard" className="nav-logo">
                <img src="/rescia-logo.png" alt="Rescia Properties" />
                <div className="nav-logo-text">
                  <span className="nav-logo-name">Rescia Properties</span>
                  <span className="nav-logo-tag">Multifamily Mastery</span>
                </div>
              </Link>
              <p>
                The complete multifamily real estate mentoring program. From market
                identification to exit &mdash; the proven system for building wealth
                through multifamily real estate.
              </p>
            </div>
          </div>
          <div className="footer-bottom">
            <div>&copy; 2026 Rescia Properties &middot; Multifamily Mastery &middot; All rights reserved</div>
            <div>Not a securities offering &middot; Past performance not indicative of future results</div>
          </div>
        </div>
      </footer>
    </>
  );
}
